#!/usr/bin/env python3

import os
import sys
import hashlib

if not os.path.exists("/etc/homework/.hidden.txt"):
    print("[!] It seems that the original file is missing, put it back!")
    sys.exit(1)

if os.path.exists("/home/workshop/folder_a/.hidden.txt"):
    print("[?] Have you forgotten to rename .hidden.txt?")
    sys.exit(1)

if os.path.exists("/home/workshop/folder_a/nothidden.txt"):
    print("[+] Good, we found the file we were looking for!")
    with open("/home/workshop/folder_a/nothidden.txt", "rb") as f:
        contents = f.read()
        if hashlib.md5(contents).hexdigest() == "e9ca1c3208fc63a3f47dba91a268bc44":
            print("[+] Contents of the file matched, you completed the exercise!")
        else:
            print("[!] The contents of the file did not match :(")
