#!/usr/bin/env python3

import os
import hashlib

piped_input = input("")

if hashlib.md5(piped_input.encode()).hexdigest() == "e48e13207341b6bffb7fb1622282247b":
    print("[+] Good, you completed the exercise!")
elif hashlib.md5(piped_input.encode()).hexdigest() == "cfcd208495d565ef66e7dff9f98764da":
    print("[+] Good, but you seem very powerful!")
else:
    print("[!] You did not complete the exercise :(")
