version: "2.4"

services:
  workshopbox:
    build: .
    image: ace-cli-box
    ports:
      - "2200-2270:22"
    restart: unless-stopped
    deploy:
      replicas: 70
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
          pids: 1000
        reservations:
          cpus: '0.02'
          memory: 30M
  
  instructorbox:
    build: .
    image: ace-cli-box
    ports:
      - "3000-3004:22"
    restart: unless-stopped
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          pids: 1000
        reservations:
          cpus: '0.05'
          memory: 100M
