version: "2.4"

services:
  workshopbox:
    build: .
    image: ace-cli-box
    ports:
      - "2200-2270:22"
    hostname: ace-cli-${id}
    deploy:
      replicas: 70
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
          pids: 1000
        reservations:
          cpus: '0.02'
          memory: 30M