version: "3.8"

# Needs to be run in a docker swarm for CPU limits

services:
  workshopbox:
    build: .
    image: ace-cli-box
    ports:
      - "2200:22"
    hostname: ace-cli-${id}
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
          pids: 1000
        reservations:
          cpus: '0.02'
          memory: 30M